// packages/svelte/src/TraceScope.svelte
<script>
  import { onMount, onDestroy, createEventDispatcher } from 'svelte'
  import { TraceScope } from 'trace-scope'
  import 'trace-scope/style'

  // Props
  export let dataSource
  export let columns        = undefined
  export let theme          = 'dark'
  export let density        = 'normal'
  export let live           = false
  export let worker         = false
  export let detail         = undefined
  export let highlightRules = []
  export let actions        = []
  export let plugins        = []
  export let locale         = 'ko-KR'

  const dispatch = createEventDispatcher()

  let container
  let _viewer = null

  const EVENTS = [
    'event:selected', 'event:deselected', 'event:action',
    'live:new-events', 'live:connected', 'live:disconnected',
    'filter:changed', 'sort:changed',
  ]

  onMount(() => {
    _viewer = new TraceScope({
      container,
      dataSource,
      columns,
      theme,
      density,
      live,
      worker,
      detail,
      highlightRules,
      actions,
      plugins,
      locale,
    })

    for (const ev of EVENTS) {
      _viewer.on(ev, (data) => dispatch(ev.replace(':', '-'), data))
    }
  })

  onDestroy(() => {
    _viewer?.destroy()
    _viewer = null
  })

  // Reactive updates
  $: if (_viewer && dataSource !== undefined) _viewer.setDataSource(dataSource)
  $: if (_viewer?._rootEl && theme)   _viewer._rootEl.dataset.tsTheme   = theme
  $: if (_viewer?._rootEl && density) _viewer._rootEl.dataset.tsDensity = density

  // Expose imperative API
  export function refresh()        { return _viewer?.refresh() }
  export function applyFilter(f)   { return _viewer?.applyFilter(f) }
  export function clearFilter()    { return _viewer?.clearFilter() }
  export function setSort(s)       { return _viewer?.setSort(s) }
  export function scrollToTop()    { return _viewer?.scrollToTop() }
  export function scrollToBottom() { return _viewer?.scrollToBottom() }
  export function pauseLive()      { return _viewer?.pauseLive() }
  export function resumeLive()     { return _viewer?.resumeLive() }
  export function clearSelection() { return _viewer?.clearSelection() }
  export function getViewer()      { return _viewer }
</script>

<div bind:this={container} class="trace-scope-svelte-wrapper" />

<style>
  .trace-scope-svelte-wrapper {
    width:  100%;
    height: 100%;
  }
</style>

// packages/vue/src/TraceScope.vue
<template>
  <div ref="containerRef" class="trace-scope-vue-wrapper" />
</template>

<script setup>
import { ref, watch, onMounted, onBeforeUnmount, toRaw } from 'vue'
import { TraceScope } from 'trace-scope'
import 'trace-scope/style'

const props = defineProps({
  dataSource:     { required: true },
  columns:        { type: Array,   default: null },
  theme:          { type: String,  default: 'dark' },
  density:        { type: String,  default: 'normal' },
  live:           { default: false },
  worker:         { default: false },
  detail:         { default: undefined },
  highlightRules: { type: Array,   default: () => [] },
  actions:        { type: Array,   default: () => [] },
  plugins:        { type: Array,   default: () => [] },
  locale:         { type: String,  default: 'ko-KR' },
})

const emit = defineEmits([
  'event:selected',
  'event:deselected',
  'event:action',
  'live:new-events',
  'live:connected',
  'live:disconnected',
  'filter:changed',
  'sort:changed',
])

const containerRef = ref(null)
let _viewer = null

const EVENTS = [
  'event:selected', 'event:deselected', 'event:action',
  'live:new-events', 'live:connected', 'live:disconnected',
  'filter:changed', 'sort:changed',
]

function createViewer() {
  if (_viewer) { _viewer.destroy(); _viewer = null }

  _viewer = new TraceScope({
    container:      containerRef.value,
    dataSource:     toRaw(props.dataSource),
    columns:        props.columns ? toRaw(props.columns) : undefined,
    theme:          props.theme,
    density:        props.density,
    live:           toRaw(props.live),
    worker:         toRaw(props.worker),
    detail:         props.detail !== undefined ? toRaw(props.detail) : undefined,
    highlightRules: toRaw(props.highlightRules),
    actions:        toRaw(props.actions),
    plugins:        toRaw(props.plugins),
    locale:         props.locale,
  })

  for (const ev of EVENTS) {
    _viewer.on(ev, (data) => emit(ev, data))
  }
}

onMounted(() => createViewer())

onBeforeUnmount(() => {
  _viewer?.destroy()
  _viewer = null
})

watch(() => props.dataSource, (ds) => {
  _viewer?.setDataSource(toRaw(ds))
})

watch(() => props.theme, (t) => {
  if (_viewer?._rootEl) _viewer._rootEl.dataset.tsTheme = t
})

watch(() => props.density, (d) => {
  if (_viewer?._rootEl) _viewer._rootEl.dataset.tsDensity = d
})

// Expose viewer instance for advanced use
defineExpose({
  viewer: () => _viewer,
  refresh:        ()  => _viewer?.refresh(),
  applyFilter:    (f) => _viewer?.applyFilter(f),
  clearFilter:    ()  => _viewer?.clearFilter(),
  setSort:        (s) => _viewer?.setSort(s),
  scrollToTop:    ()  => _viewer?.scrollToTop(),
  scrollToBottom: ()  => _viewer?.scrollToBottom(),
  pauseLive:      ()  => _viewer?.pauseLive(),
  resumeLive:     ()  => _viewer?.resumeLive(),
  destroy:        ()  => _viewer?.destroy(),
})
</script>

<style scoped>
.trace-scope-vue-wrapper {
  width:  100%;
  height: 100%;
}
</style>
